# This will publish a new app release
name: Electron Forge Publisher GitHub

# Write permissions are required to create new releases.
permissions:
  contents: write

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Electron Forge Publisher GitHub
        run: |
          npm i
          npm run publish
