# This will publish a new app release
name: Electron Forge Publisher GitHub

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    # Write permissions are required to create new releases.
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Electron Forge Publisher GitHub
        run: |
          npm i
          npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
